# Generated by Django 4.2.2 on 2023-06-26 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('robot_controller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secuenciacombinada',
            name='elemento1',
        ),
        migrations.RemoveField(
            model_name='secuenciacombinada',
            name='elemento2',
        ),
        migrations.RemoveField(
            model_name='secuenciacombinada',
            name='elemento3',
        ),
        migrations.RemoveField(
            model_name='secuenciacombinada',
            name='elemento4',
        ),
        migrations.RemoveField(
            model_name='secuenciacombinada',
            name='elemento5',
        ),
        migrations.AddField(
            model_name='secuenciacombinada',
            name='elemento1_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='secuenciacombinada',
            name='elemento1_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secuencia_combinada_elemento1', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='secuenciacombinada',
            name='elemento2_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='secuenciacombinada',
            name='elemento2_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secuencia_combinada_elemento2', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='secuenciacombinada',
            name='elemento3_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secuenciacombinada',
            name='elemento3_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secuencia_combinada_elemento3', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='secuenciacombinada',
            name='elemento4_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secuenciacombinada',
            name='elemento4_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secuencia_combinada_elemento4', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='secuenciacombinada',
            name='elemento5_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secuenciacombinada',
            name='elemento5_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secuencia_combinada_elemento5', to='contenttypes.contenttype'),
        ),
    ]
