# Generated by Django 4.2.1 on 2023-06-18 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etiquetas',
            fields=[
                ('id_etiqueta', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=45)),
                ('orden', models.IntegerField()),
                ('id_etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_com_xcelera.etiquetas', verbose_name='Etiqueta relacionada')),
            ],
        ),
        migrations.CreateModel(
            name='Submovimientos',
            fields=[
                ('id_submovimiento', models.BigAutoField(primary_key=True, serialize=False)),
                ('join_1', models.DecimalField(decimal_places=2, max_digits=3)),
                ('join_2', models.DecimalField(decimal_places=2, max_digits=3)),
                ('join_3', models.DecimalField(decimal_places=2, max_digits=3)),
                ('join_4', models.DecimalField(decimal_places=2, max_digits=3)),
                ('join_5', models.DecimalField(decimal_places=2, max_digits=3)),
                ('velocidad', models.DecimalField(decimal_places=2, max_digits=3)),
                ('id_movimiento', models.ManyToManyField(to='app_com_xcelera.movimientos', verbose_name='Movimiento relacionado')),
            ],
        ),
    ]
