# Generated by Django 4.2.1 on 2023-06-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_com_xcelera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submovimientos',
            name='id_movimiento',
            field=models.ManyToManyField(default=1, to='app_com_xcelera.movimientos', verbose_name='Movimiento relacionado'),
        ),
    ]
