# Generated by Django 4.2.1 on 2023-06-18 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_com_xcelera', '0002_alter_submovimientos_id_movimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submovimientos',
            name='id_movimiento',
        ),
        migrations.AddField(
            model_name='submovimientos',
            name='id_movimiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_com_xcelera.movimientos', verbose_name='Movimiento relacionado'),
        ),
    ]
