# Generated by Django 4.2.1 on 2023-06-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_com_xcelera', '0003_remove_submovimientos_id_movimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submovimientos',
            name='join_1',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='submovimientos',
            name='join_2',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='submovimientos',
            name='join_3',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='submovimientos',
            name='join_4',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='submovimientos',
            name='join_5',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='submovimientos',
            name='velocidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
