# Generated by Django 4.2.1 on 2023-06-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_com_xcelera', '0004_alter_submovimientos_join_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientos',
            name='id_etiqueta',
        ),
        migrations.AddField(
            model_name='movimientos',
            name='etiquetas',
            field=models.ManyToManyField(related_name='movimientos', to='app_com_xcelera.etiquetas'),
        ),
    ]
