# Generated by Django 4.2.2 on 2023-06-26 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puntos',
            fields=[
                ('id_punto', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('angulo1', models.FloatField()),
                ('angulo2', models.FloatField()),
                ('angulo3', models.FloatField()),
                ('angulo4', models.FloatField()),
                ('angulo5', models.FloatField()),
                ('velocidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SecuenciaCombinada',
            fields=[
                ('id_secuencia_combinada', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre_secuencia_combinada', models.CharField(max_length=50)),
                ('elemento1', models.CharField(max_length=50)),
                ('elemento2', models.CharField(max_length=50)),
                ('elemento3', models.CharField(max_length=50)),
                ('elemento4', models.CharField(max_length=50)),
                ('elemento5', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SecuenciaPuntos',
            fields=[
                ('id_secuencia_puntos', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre_secuencia', models.CharField(max_length=50)),
                ('punto1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secuencia_puntos_punto1', to='robot_controller.puntos')),
                ('punto2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secuencia_puntos_punto2', to='robot_controller.puntos')),
                ('punto3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secuencia_puntos_punto3', to='robot_controller.puntos')),
                ('punto4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secuencia_puntos_punto4', to='robot_controller.puntos')),
                ('punto5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secuencia_puntos_punto5', to='robot_controller.puntos')),
            ],
        ),
    ]
