# Generated by Django 4.2.2 on 2023-06-26 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robot_controller', '0002_remove_secuenciacombinada_elemento1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secuenciacombinada',
            name='elemento1_id',
        ),
        migrations.RemoveField(
            model_name='secuenciacombinada',
            name='elemento1_type',
        ),
        migrations.RemoveField(
            model_name='secuenciacombinada',
            name='elemento2_id',
        ),
        migrations.RemoveField(
            model_name='secuenciacombinada',
            name='elemento2_type',
        ),
        migrations.RemoveField(
            model_name='secuenciacombinada',
            name='elemento3_id',
        ),
        migrations.RemoveField(
            model_name='secuenciacombinada',
            name='elemento3_type',
        ),
        migrations.RemoveField(
            model_name='secuenciacombinada',
            name='elemento4_id',
        ),
        migrations.RemoveField(
            model_name='secuenciacombinada',
            name='elemento4_type',
        ),
        migrations.RemoveField(
            model_name='secuenciacombinada',
            name='elemento5_id',
        ),
        migrations.RemoveField(
            model_name='secuenciacombinada',
            name='elemento5_type',
        ),
        migrations.AddField(
            model_name='secuenciacombinada',
            name='pp1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secuencia_combinada_pp1', to='robot_controller.puntos'),
        ),
        migrations.AddField(
            model_name='secuenciacombinada',
            name='pp2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secuencia_combinada_pp2', to='robot_controller.puntos'),
        ),
        migrations.AddField(
            model_name='secuenciacombinada',
            name='pp3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secuencia_combinada_pp3', to='robot_controller.puntos'),
        ),
        migrations.AddField(
            model_name='secuenciacombinada',
            name='pp4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secuencia_combinada_pp4', to='robot_controller.puntos'),
        ),
        migrations.AddField(
            model_name='secuenciacombinada',
            name='pp5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secuencia_combinada_pp5', to='robot_controller.puntos'),
        ),
        migrations.AddField(
            model_name='secuenciacombinada',
            name='sp1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secuencia_combinada_sp1', to='robot_controller.secuenciapuntos'),
        ),
        migrations.AddField(
            model_name='secuenciacombinada',
            name='sp2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secuencia_combinada_sp2', to='robot_controller.secuenciapuntos'),
        ),
        migrations.AddField(
            model_name='secuenciacombinada',
            name='sp3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secuencia_combinada_sp3', to='robot_controller.secuenciapuntos'),
        ),
        migrations.AddField(
            model_name='secuenciacombinada',
            name='sp4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secuencia_combinada_sp4', to='robot_controller.secuenciapuntos'),
        ),
        migrations.AddField(
            model_name='secuenciacombinada',
            name='sp5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secuencia_combinada_sp5', to='robot_controller.secuenciapuntos'),
        ),
    ]
